- name: Ensure .ssh directory exists
  file:
    path: /home/{{ ansible_user }}/.ssh
    state: directory
    mode: '0700'

- name: Install SSH public key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
